### ISSUE TITLE
values changed by MIDI dont update the screen values

### ISSUE THREAD

**Issue by synthi** [whosebodyisthis/guttersyn#1]
Trying your script, lovely! just binded the parameters to my 16n controller and all is working working but the norns screen values dont change

**Comment by whosebodyisthis** [comment]
I think I know what the issue is, since I don't really use MIDI/external control I neglected the fact the screen won't update unless the norns encoders/buttons are used. will try and fix this later today, thanks for pointing this out!

**Comment by whosebodyisthis** [comment]
External control should now be reflected with screen slider changes. Previously, the screen would only update when an encoder/button is used. Now, a metro updates the screen at a rate of 30fps.
